//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int mm { get; set; }
        public int movieid { get; set; }
        public int perid { get; set; }
    
        public virtual film film { get; set; }
        public virtual person person { get; set; }
    }
}
